# Pre-commit hooks to prevent sensitive data commits
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']
  
  - repo: local
    hooks:
      - id: credential-scanner
        name: Scan for credentials
        entry: python scripts/scan_credentials.py
        language: python
        files: .*
        stages: [commit]
      
      - id: block-sensitive-files
        name: Block sensitive file patterns
        entry: bash -c 'if git diff --cached --name-only | grep -E "(credential|password|secret|\.env|test_.*\.py$)"; then echo "❌ BLOCKED: Attempting to commit sensitive files!"; exit 1; fi'
        language: system
        stages: [commit]